projects:

  app:
    schemaPath: api/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:3001/graphql

  prisma:
    schemaPath: shared/prisma/types.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: flow
        output:
          binding: shared/prisma/types.js
