// flow-typed signature: 0a8424ab437b412916def473f1e47828
// flow-typed version: <<STUB>>/flow-node_v1.2.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-node/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-node/index' {
  declare module.exports: $Exports<'flow-node'>;
}
declare module 'flow-node/index.js' {
  declare module.exports: $Exports<'flow-node'>;
}
declare module 'flow-node/register.js' {
  declare module.exports: $Exports<'flow-node/register'>;
}
