// flow-typed signature: 079821f79b5c4787af438f205d08498e
// flow-typed version: <<STUB>>/graphql-binding_v2.2.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-binding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-binding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-binding/dist/bin' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/Binding' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/FlowGenerator' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/FlowGenerator.test' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/Generator' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/Generator.test' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/types' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/TypescriptGenerator' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/TypescriptGenerator.test' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/utils/flatten' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/codegen/utils/interleave' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/Delegate' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/fragmentReplacements' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/info' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/info.test' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/makeBindingClass' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/types' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/utils/addFragmentToInfo' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/utils/addFragmentToInfo.test' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/utils/index' {
  declare module.exports: any;
}

declare module 'graphql-binding/dist/utils/removeKey' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-binding/dist/bin.js' {
  declare module.exports: $Exports<'graphql-binding/dist/bin'>;
}
declare module 'graphql-binding/dist/Binding.js' {
  declare module.exports: $Exports<'graphql-binding/dist/Binding'>;
}
declare module 'graphql-binding/dist/codegen/FlowGenerator.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/FlowGenerator'>;
}
declare module 'graphql-binding/dist/codegen/FlowGenerator.test.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/FlowGenerator.test'>;
}
declare module 'graphql-binding/dist/codegen/Generator.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/Generator'>;
}
declare module 'graphql-binding/dist/codegen/Generator.test.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/Generator.test'>;
}
declare module 'graphql-binding/dist/codegen/types.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/types'>;
}
declare module 'graphql-binding/dist/codegen/TypescriptGenerator.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/TypescriptGenerator'>;
}
declare module 'graphql-binding/dist/codegen/TypescriptGenerator.test.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/TypescriptGenerator.test'>;
}
declare module 'graphql-binding/dist/codegen/utils/flatten.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/utils/flatten'>;
}
declare module 'graphql-binding/dist/codegen/utils/interleave.js' {
  declare module.exports: $Exports<'graphql-binding/dist/codegen/utils/interleave'>;
}
declare module 'graphql-binding/dist/Delegate.js' {
  declare module.exports: $Exports<'graphql-binding/dist/Delegate'>;
}
declare module 'graphql-binding/dist/fragmentReplacements.js' {
  declare module.exports: $Exports<'graphql-binding/dist/fragmentReplacements'>;
}
declare module 'graphql-binding/dist/index.js' {
  declare module.exports: $Exports<'graphql-binding/dist/index'>;
}
declare module 'graphql-binding/dist/info.js' {
  declare module.exports: $Exports<'graphql-binding/dist/info'>;
}
declare module 'graphql-binding/dist/info.test.js' {
  declare module.exports: $Exports<'graphql-binding/dist/info.test'>;
}
declare module 'graphql-binding/dist/makeBindingClass.js' {
  declare module.exports: $Exports<'graphql-binding/dist/makeBindingClass'>;
}
declare module 'graphql-binding/dist/types.js' {
  declare module.exports: $Exports<'graphql-binding/dist/types'>;
}
declare module 'graphql-binding/dist/utils/addFragmentToInfo.js' {
  declare module.exports: $Exports<'graphql-binding/dist/utils/addFragmentToInfo'>;
}
declare module 'graphql-binding/dist/utils/addFragmentToInfo.test.js' {
  declare module.exports: $Exports<'graphql-binding/dist/utils/addFragmentToInfo.test'>;
}
declare module 'graphql-binding/dist/utils/index.js' {
  declare module.exports: $Exports<'graphql-binding/dist/utils/index'>;
}
declare module 'graphql-binding/dist/utils/removeKey.js' {
  declare module.exports: $Exports<'graphql-binding/dist/utils/removeKey'>;
}
