// flow-typed signature: dcd22b41f2a347eca337f521113ba0bf
// flow-typed version: <<STUB>>/keygrip_v1.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keygrip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keygrip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keygrip/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keygrip/index' {
  declare module.exports: $Exports<'keygrip'>;
}
declare module 'keygrip/index.js' {
  declare module.exports: $Exports<'keygrip'>;
}
declare module 'keygrip/test.js' {
  declare module.exports: $Exports<'keygrip/test'>;
}
