// flow-typed signature: 95c868db1c34067b07668b978d1c6d69
// flow-typed version: <<STUB>>/prisma_v1.11.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prisma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prisma' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prisma/dist/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'prisma/dist/index.js' {
  declare module.exports: $Exports<'prisma/dist/index'>
}
