// flow-typed signature: 4c6928e0f9f2fa2acb2136c4a85ea465
// flow-typed version: <<STUB>>/qs-middleware_v1.0.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qs-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qs-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qs-middleware/lib/qs-middleware' {
  declare module.exports: any;
}

declare module 'qs-middleware/test/unit/lib/qs-middleware' {
  declare module.exports: any;
}

declare module 'qs-middleware/test/unit/mock/qs' {
  declare module.exports: any;
}

declare module 'qs-middleware/test/unit/mock/url' {
  declare module.exports: any;
}

declare module 'qs-middleware/test/unit/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qs-middleware/lib/qs-middleware.js' {
  declare module.exports: $Exports<'qs-middleware/lib/qs-middleware'>;
}
declare module 'qs-middleware/test/unit/lib/qs-middleware.js' {
  declare module.exports: $Exports<'qs-middleware/test/unit/lib/qs-middleware'>;
}
declare module 'qs-middleware/test/unit/mock/qs.js' {
  declare module.exports: $Exports<'qs-middleware/test/unit/mock/qs'>;
}
declare module 'qs-middleware/test/unit/mock/url.js' {
  declare module.exports: $Exports<'qs-middleware/test/unit/mock/url'>;
}
declare module 'qs-middleware/test/unit/setup.js' {
  declare module.exports: $Exports<'qs-middleware/test/unit/setup'>;
}
