// flow-typed signature: 50d51d1336640a778ab13874dc6a7cb9
// flow-typed version: <<STUB>>/react-image_v1.3.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image/cjs/index' {
  declare module.exports: any;
}

declare module 'react-image/es/index' {
  declare module.exports: any;
}

declare module 'react-image/umd/index' {
  declare module.exports: any;
}

declare module 'react-image/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image/cjs/index.js' {
  declare module.exports: $Exports<'react-image/cjs/index'>;
}
declare module 'react-image/es/index.js' {
  declare module.exports: $Exports<'react-image/es/index'>;
}
declare module 'react-image/umd/index.js' {
  declare module.exports: $Exports<'react-image/umd/index'>;
}
declare module 'react-image/umd/index.min.js' {
  declare module.exports: $Exports<'react-image/umd/index.min'>;
}
