FROM therepm/installer:latest AS installer

# -----------------------------------------------------------------------------
# development
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as development
WORKDIR /app

COPY --from=installer /app/node_modules /app/node_modules
COPY --from=installer /app/web/node_modules /app/web/node_modules

CMD ["yarn", "dev:web"]

# -----------------------------------------------------------------------------
# build
# -----------------------------------------------------------------------------
FROM development as builder

COPY . /app
RUN yarn build:web -o /public

# -----------------------------------------------------------------------------
# production
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine
WORKDIR /app

COPY --from=builder /public /public

ENV NODE_ENV=production